extends:
  - stylelint-scss
  - stylelint-config-recommended
plugins:
  - stylelint-scss
ignoreFiles:
  - 'assets/scss/govuk/**/*.*'
rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  no-descending-specificity: null
  selector-type-no-unknown: null
  no-invalid-position-at-import-rule: null