# Host to use for canonical URL generation (without trailing slash)
host: ##PAGES_URL##

# Header-related options
show_govuk_logo: false
service_name: ##SERVICE_NAME##
service_link: ##PAGES_PATH##
phase: INTERNAL

# Links to show on right-hand-side of header
header_links:
  GitLab: ##PROJECT_URL##
  Documentation: ##PAGES_PATH##

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: false
# github_repo: alphagov/YOUR_REPO

#api_path directive is not supported for static site generation - see readme for further details
#api_path: 



